project_id = "gugduludshezdsplkkxu"

[functions.refresh-fx-rates]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.sync-ical]
verify_jwt = false

[functions.ical-export]
verify_jwt = false
